name: CI

on:
  push:
    branches:
      - 'trunk'
      - '4.4'
      - '4.3'
      - '4.2'

  schedule:
    - cron: '0 0 * * 6,0'    # Run on Saturday and Sunday at midnight UTC

  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]
    branches:
      - 'trunk'
      - '4.4'
      - '4.3'
      - '4.2'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      is-trunk: ${{ github.ref == 'refs/heads/trunk' }}
      is-public-fork: ${{ github.event.pull_request.head.repo.fork || false }}
    secrets:
      inherit
